title: Bibledit
email: teusjannette@gmail.com
description: Bibledit.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://bibledit.org' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ''
github_username: ''

# Build settings
# theme: minima
theme: minimax
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: 'posts' # empty string means all files
    values:
      layout: 'post'
      author: 'John Doe'
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
